quanlytruonghop/quanly/quanly/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader import views as ckeditor_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('topicyeucau.urls')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quanlytruonghop/quanly/topicyeucau/urls.py
from django.urls import path,include
from .views import home_view,create_request,login_view,logout_view,update_user_profile,my_topic_detail,mytopic,ArticleDetailView,manage_view,manage_request,rate_topic,KnowledgeDetailView,article_update_view,article_delete_view ,article_hide_view,article_unhide_view
from .views import create_article,article_list,create_knowledge,knowledge_list
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
from . import views 

urlpatterns = [

    path('microsoft_authentication/callback', views.microsoft_callback, name='microsoft_callback'),
    path('',home_view,name='home'),
 
    path('signin', views.sign_in, name='signin'),
    path('signout', views.sign_out, name='signout'),
    path('callback', views.callback, name='callback'),





    path('create_request/',create_request,name='create_request'),
    path('account/my-topic/', mytopic, name='my-topic'),
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
    
    path('update_profile/', update_user_profile, name='account_profile'),
    path('topic/<int:id>/', my_topic_detail, name='topic_detail'),
    path('create_acticle/', create_article, name='create_article'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('article_list/', article_list, name='article_list'),
    path('article/<int:pk>/update/', article_update_view, name='article_update_view'),
    path('article/<int:pk>/delete/', article_delete_view, name='article_delete_view'),
    path('article/<int:pk>/hide/', article_hide_view, name='article_hide_view'),
    path('article/<int:pk>/unhide/', article_unhide_view, name='article_unhide_view'),
    
    path('knowledge/<int:pk>/', KnowledgeDetailView.as_view(), name='knowledge_detail'),
    path('create_knowledge/', create_knowledge, name='create_knowledge'),
    path('knowledge_list/', knowledge_list, name='knowledge_list'),
    



    path('manage/',manage_view,name='manage_view'),
    path('manage_request/',manage_request,name='manage_request'),
    path('rate/',rate_topic,name='rate-view'),



    

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quanlytruonghop/quanly/topicyeucau/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.validators import RegexValidator
from django.contrib.auth.models import Group
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import timedelta
from django.urls import reverse
import pytz

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Email field is required')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if not extra_fields.get('is_staff'):
            raise ValueError('Superuser must have is_staff=True')
        if not extra_fields.get('is_superuser'):
            raise ValueError('Superuser must have is_superuser=True')

        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    cus_id = models.CharField(max_length=10,default=0)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    role = models.CharField(max_length=10, choices=(('student', 'Student'), ('teacher', 'Teacher')), default='student')
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255,default='Họ và Tên')
    phone_regex = RegexValidator(regex=r'^\d{10}$', message="Số điện thoại phải có 10 chữ số.")
    phone = models.CharField(validators=[phone_regex], max_length=10, blank=True, null=True)
    student_id = models.CharField(max_length=10)
    course = models.CharField(max_length=50)
    avatar = models.ImageField(upload_to='avatars/', default='avatars/default.jpg')
    role = models.CharField(max_length=255, default='Sinh viên')
    

    def __str__(self):
        return self.user.username
    
class Knowledge(models.Model):
    category = models.CharField(max_length=255)
    content = models.CharField(max_length=255,blank=True,null=True)
    image = models.ImageField(upload_to='images/knowledge', blank=True, null=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    url = models.CharField(max_length=255,blank=True,null=True)
    

    def __str__(self):
        return self.category

class Article(models.Model):
    title = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    content = RichTextUploadingField(blank=True, null=True)
    image = models.ImageField(upload_to='articles/', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    views = models.PositiveIntegerField(default=0)
    like_count = models.PositiveIntegerField(default=0)
    hidden = models.BooleanField(default=False)
    knowledge = models.ForeignKey(Knowledge, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        if self.knowledge and self.knowledge.url:
            return self.knowledge.url
        return reverse('article_detail', args=[str(self.id)])

    

    def add_like(self, user):
        if user not in self.likes.all():
            self.likes.add(user)
            self.like_count += 1
            self.save()

    




class Image(models.Model):
    image = models.ImageField(upload_to='images/topic')

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    request_count = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name

class Topic(models.Model):
    TITLE_MAX_LENGTH = 200
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    content = RichTextUploadingField(blank=True, null=True)
    image = models.ImageField(upload_to='images/topic', blank=True, null=True, default=None)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='topics')
    start_time = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)


    def save(self, *args, **kwargs):
        # Tăng request_count của category liên kết
        self.category.request_count += 1
        self.category.save()
        super(Topic, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    




class MyTopic(models.Model):
    CHOICES = (
        ('Đang xử lý', 'Đang xử lý'),
        ('Hoàn thành', 'Hoàn thành'),
    )
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE) 
    employee = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    cus_id = models.CharField(max_length=20,blank=True) 
    status = models.CharField(max_length=20, choices=CHOICES, default='Chờ tiếp nhận')
    start_time = models.DateTimeField(auto_now_add=True)
    start_time_request= models.DateTimeField(null=True, blank=True)
    start_time_employee = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    elapsed_time = models.IntegerField(null=True, blank=True,default=0)

    def save(self, *args, **kwargs):
        if self.start_time_request and self.end_time:
            elapsed_time = self.end_time - self.start_time_request
            self.elapsed_time = int(elapsed_time.total_seconds() // 60)  # Chuyển đổi thành phút và chuyển thành số nguyên
        super().save(*args, **kwargs)
        
    def get_formatted_start_time_request(self):
        vietnam_tz = pytz.timezone('Asia/Ho_Chi_Minh')
        start_time_request = self.start_time_request.astimezone(vietnam_tz)
        return start_time_request.strftime("%d/%m/%Y %H:%M:%S")

    def get_formatted_start_time(self):
        vietnam_tz = pytz.timezone('Asia/Ho_Chi_Minh')
        start_time = self.start_time.astimezone(vietnam_tz)
        return start_time.strftime("%d/%m/%Y %H:%M:%S")

    def get_formatted_start_time_employee(self):
        vietnam_tz = pytz.timezone('Asia/Ho_Chi_Minh')
        start_time_employee = self.start_time_employee.astimezone(vietnam_tz)
        return start_time_employee.strftime("%d/%m/%Y %H:%M:%S")
    
    def get_formatted_end_time(self):
        vietnam_tz = pytz.timezone('Asia/Ho_Chi_Minh')
        end_time = self.end_time.astimezone(vietnam_tz)
        return end_time.strftime("%d/%m/%Y %H:%M:%S")

    def get_formatted_elapsed_time(self):
        hours = self.elapsed_time // 60
        minutes = self.elapsed_time % 60
        seconds = 0
        formatted_elapsed_time = "{:02d}:{:02d}:{:02d}".format(hours, minutes, seconds)
        return formatted_elapsed_time

    def __str__(self):
        return self.topic.title

    @property
    def topic_title(self):
        return self.topic.title
    
    @property
    def topic_content(self):
        return self.topic.content
    
    @property
    def topic_author(self):
        return self.topic.author

    @property
    def name(self):
        return self.employee.username if self.employee else ""
    



class Rating(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    score = models.IntegerField(default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0),
        ]
    )

    def __str__(self):
        return self.topic.title
    
    @property
    def topic_title(self):
        return self.topic.title
    
    @property
    def topic_content   (self):
        return self.topic.content
    
    @property
    def topic_author(self):
        return self.topic.author

    






class TopicSubmission(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    cus_id = models.CharField(max_length=20)
    status = models.CharField(max_length=20, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} - {self.topic.title}'
    

quanlytruonghop/quanly/topicyeucau/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Topic,UserProfile,Category,MyTopic,Article,Knowledge
from django.core.validators import RegexValidator
from django.contrib.auth.models import Group,User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserProfileForm(forms.ModelForm):
    phone = forms.CharField(label='Số điện thoại', max_length=10, validators=[RegexValidator('^[0-9]*$', 'Vui lòng chỉ nhập số')])
    
    class Meta:
        model = UserProfile
        fields = ('avatar', 'phone',)
        labels = {
            'avatar': 'Ảnh đại diện'
        }
        widgets = {
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'})
        }



class CustomModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        profile, created = UserProfile.objects.get_or_create(user=obj)
        return profile.name

class AssignTopicForm(forms.ModelForm):
    employee = CustomModelChoiceField(queryset=UserProfile.objects.all(), label='Nhân viên')

    class Meta:
        model = MyTopic
        fields = ['employee']
        labels = {
            'employee': 'Nhân viên',
        }

    def __init__(self, *args, **kwargs):
        self.is_end_time_updated = False
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['employee'].queryset = self.get_available_employees()

        self.is_end_time_updated = False

    def get_available_employees(self):
        employees = User.objects.filter(groups__name='Employee')
        if self.instance.pk:
            assigned_employees = MyTopic.objects.exclude(pk=self.instance.pk).filter(status='Đang xử lý').values_list('employee_id', flat=True)
            employees = employees.exclude(pk__in=assigned_employees)
        return employees
    
    def clean_employee(self):
        employee = self.cleaned_data['employee']
        if employee is not None:
            self.instance.status = 'Đang xử lý'
            self.instance.start_time_employee = timezone.now()
            # Tạo UserProfile nếu chưa tồn tại
            UserProfile.objects.get_or_create(user=employee)
        return employee

    
    def clean(self):
        cleaned_data = super().clean()
        status = cleaned_data.get('status')
        if status == 'Hoàn thành' and not self.is_end_time_updated:
            self.instance.status = status
            self.instance.end_time = timezone.now()
            self.is_end_time_updated = True
        return cleaned_data

class KnowledgeForm(forms.ModelForm):
    class Meta:
        model = Knowledge
        fields = ['category', 'content', 'image']
        labels = {
            'category': 'Thể loại',
            'content':'Nội dung',
            'image':'Hình ảnh',
        }
    

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {
            'name':'Tên thể loại',
        }  
    
    
class ArticleForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget(config_name='default'))
    class Meta:
        model = Article
        fields = ['title', 'category','content', 'image','knowledge']
        labels = {
            'title':'Chủ đề',
            'category': 'Thể loại',
            'content':'Nội dung',
            'image':'Hình ảnh',
            'knowledge':'Knowledge',
        }



class TopicForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget(config_name='default'))
    category = forms.ModelChoiceField(queryset=Category.objects.all(), to_field_name='name')

    class Meta:
        model = Topic
        fields = ['title', 'category','content', 'image']
        labels = {
            'title':'Chủ đề',
            'category': 'Thể loại',
            'content':'Nội dung',
            'image':'Hình ảnh',
        }

quanlytruonghop/quanly/topicyeucau/templates/client/articles/article_detail.html
{% extends 'client/base.html' %}


{% block title %} {{article.title}} {% endblock %}

{%block style%}
<style>
  .container {
    margin-top: 100px
  }

  .breadcrumbs {
    display: flex;
    align-items: center;
    font-size: 16px;
    margin-bottom: 20px;
    justify-content: flex-start;
  }

  .breadcrumbs li {
    list-style: none;
  }

  .breadcrumbs li:not(:last-child)::after {
    content: '>';
    margin: 0 10px;
  }

  .breadcrumbs li a {
    color: #666;
    text-decoration: none;
  }

  .breadcrumbs li a:hover {

    text-decoration: none;
  }

  p img {
    display: block;
    max-width: 100%;
    height: auto;
    margin: 0;
  }

  picture img {
    display: block;
    max-width: 100%;
    height: auto;
    margin: 0;
  }

  .author-info {
    display: flex;
    align-items: center;
    margin-bottom: 20px;
  }

  .author-icon {
    width: 50px;
    height: 50px;
    border-radius: 50%;
    margin-right: 10px;
  }

  .author-details {
    display: flex;
    flex-direction: column;
  }

  .author-name {
    font-size: 16px;
    font-weight: bold;
    margin: 0;
  }

  .publish-date {
    font-size: 14px;
    margin: 0;
  }

  .left-menu {
    margin-top: -40px;
  }
  footer.text-center.text-lg-start.custom-footer {
    margin-top: 160px;
  }
</style>

{% endblock %}

{%block body%}
<div class="container">
  <div class="column column--sm-8">
    <ol class="breadcrumbs">
      <li><a href="{% url 'home' %}">Home</a></li>
      {% if knowledge %}
        <li><a href="{% url 'knowledge_detail' knowledge.pk %}">{{ knowledge.category }}</a></li>
      {% else %}
        <li><a href="">Knowledge</a></li>
      {% endif %}
      <li><a href="">Article</a></li>
    </ol>
  </div>
  <h1 class="mt-4 mb-3"></h1>
  <h2>{{ article.title }}</h2>
  <div class="author-info">
    <img src="{{ article.author.userprofile.avatar.url }}" alt="Author Icon" class="author-icon">
    <div class="author-details">
      <p class="author-name">{{ article.author }}</p>
      <p class="publish-date">{{ article.created_at }}</p>
    </div>
  </div>
  <p>{{article.content|safe}}</p>
  {% if article.image %}
  <picture class="text-center">
    <source srcset="{{ article.image.url }}?w=480" media="(max-width: 480px)">
    <source srcset="{{ article.image.url }}?w=768" media="(max-width: 768px)">
    <source srcset="{{ article.image.url }}?w=1024" media="(max-width: 1024px)">
    <source srcset="{{ article.image.url }}?w=1920" media="(max-width: 1920px)">
    <img src="{{ article.image.url }}" alt="{{ article.title }}">
  </picture>
  {% endif %}
  {% if user.is_authenticated and user == article.author %}
    <a href="{% url 'article_update_view' article.pk %}" class="btn btn-primary">Cập nhật</a>
    <form action="{% url 'article_delete_view' article.pk %}" method="post" class="d-inline">
      {% csrf_token %}
      <input type="submit" value="Xoá bài viết" class="btn btn-danger" onclick="return confirm('Bạn có chắc chắn muốn xoá bài viết này?')">
    </form>
    {% if article.hidden %}
      <form method="POST" action="{% url 'article_unhide_view' article.pk %}">
        {% csrf_token %}

        <input type="submit" value="Hiện bài viết" class="btn btn-warning" onclick="return confirm('Bạn có muốn hiện bài viết này?')">
      </form>
    {% else %}
      <form method="POST" action="{% url 'article_hide_view' article.pk %}">
        {% csrf_token %}
        <input type="submit" value="Ẩn bài viết" class="btn btn-warning" onclick="return confirm('Bạn có muốn ẩn bài viết này?')">
      </form>
    {% endif %}
  
  {% endif %}



</div>




</div>


{% block footer%}{% endblock %}

{% endblock %}

quanlytruonghop/quanly/topicyeucau/templates/client/articles/article_update.html
{% extends "client/base.html" %}
{% block title %}
Bài viết
{% endblock %}

{% block style %}
<style>
  /* Custom styles for create_request.html */

  .card-header {
    background-color: #007bff;
    color: white;
  }

  .btn-primary {
    background-color: #007bff;
    border-color: #007bff;
  }

  .btn-primary:hover {
    background-color: #0069d9;
    border-color: #0062cc;
  }

  .btn-primary:focus,
  .btn-primary.focus {
    box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.5);
  }

  .btn-primary.disabled,
  .btn-primary:disabled {
    background-color: #007bff;
    border-color: #007bff;
  }

  .btn-primary:not(:disabled):not(.disabled):active,
  .btn-primary:not(:disabled):not(.disabled).active,
  .show>.btn-primary.dropdown-toggle {
    background-color: #0062cc;
    border-color: #005cbf;
  }

  .btn-primary:not(:disabled):not(.disabled):active:focus,
  .btn-primary:not(:disabled):not(.disabled).active:focus,
  .show>.btn-primary.dropdown-toggle:focus {
    box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.5);
  }

  .topic-image {
    max-width: 100%;
    height: auto;
  }

  input#id_title {
    width: 100%;
  }

  input#id_category {
    width: 100%;
  }

  input#id_image {
    padding: 20px;
    margin-top: 10px;
    width: 100%;
    border: 1px solid;
    /* justify-content: center; */
  }

  .col-md-6.offset-md-4 {
    margin: 0;
    margin-top: 10px;
  }

  .left-menu {
    margin-top: 13px;
  }
</style>
{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {% if article.pk %}
                    <h3 class="text-center">Chỉnh sửa bài viết</h3>
                    {% else %}
                    <h3 class="text-center">Viết bài báo</h3>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                {% if article.image %}
                <div class="card-footer">
                    <img src="{{ article.image.url }}" class="topic-image">
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

quanlytruonghop/quanly/topicyeucau/templates/client/articles/create_article.html
{% extends "client/base.html" %}
{% block title %}
Bài viết
{% endblock %}

{% block style %}
<style>
  /* Custom styles for create_request.html */

  .card-header {
    background-color: #007bff;
    color: white;
  }

  .btn-primary {
    background-color: #007bff;
    border-color: #007bff;
  }

  .btn-primary:hover {
    background-color: #0069d9;
    border-color: #0062cc;
  }

  .btn-primary:focus,
  .btn-primary.focus {
    box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.5);
  }

  .btn-primary.disabled,
  .btn-primary:disabled {
    background-color: #007bff;
    border-color: #007bff;
  }

  .btn-primary:not(:disabled):not(.disabled):active,
  .btn-primary:not(:disabled):not(.disabled).active,
  .show>.btn-primary.dropdown-toggle {
    background-color: #0062cc;
    border-color: #005cbf;
  }

  .btn-primary:not(:disabled):not(.disabled):active:focus,
  .btn-primary:not(:disabled):not(.disabled).active:focus,
  .show>.btn-primary.dropdown-toggle:focus {
    box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.5);
  }

  .topic-image {
    max-width: 100%;
    height: auto;
  }

  input#id_title {
    width: 100%;
  }

  input#id_category {
    width: 100%;
  }

  input#id_image {
    padding: 20px;
    margin-top: 10px;
    width: 100%;
    border: 1px solid;
    /* justify-content: center; */
  }

  #id_knowledge {
    width: 100%;
  }

  .col-md-6.offset-md-4 {
    margin: 0;
    margin-top: 10px;
  }

  .left-menu {
    margin-top: 13px;
  }
  

</style>
{% endblock %}

{% block body %}
<div class="container mt-5">

  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h3 class="text-center">Viết bài báo</h3>
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-group row">
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </form>
        </div>
        {% if form.instance.image %}
        <div class="card-footer">
          <img src="{{ form.instance.image.url }}" class="topic-image">
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}