quanlytruonghop/quanly/quanly/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader import views as ckeditor_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('topicyeucau.urls')),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quanlytruonghop/quanly/topicyeucau/urls.py
from django.urls import path,include
from .views import home_view,create_request,login_view,logout_view,update_user_profile,my_topic_detail,mytopic,ArticleDetailView,manage_view,manage_request,rate_topic,KnowledgeDetailView,article_update_view,article_delete_view ,article_hide_view,article_unhide_view
from .views import create_article,article_list,create_knowledge,knowledge_list
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
from . import views 

urlpatterns = [

    path('microsoft_authentication/callback', views.microsoft_callback, name='microsoft_callback'),
    path('',home_view,name='home'),
 
    path('signin', views.sign_in, name='signin'),
    path('signout', views.sign_out, name='signout'),
    path('callback', views.callback, name='callback'),





    path('create_request/',create_request,name='create_request'),
    path('account/my-topic/', mytopic, name='my-topic'),
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
    
    path('update_profile/', update_user_profile, name='account_profile'),
    path('topic/<int:id>/', my_topic_detail, name='topic_detail'),
    path('create_acticle/', create_article, name='create_article'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('article_list/', article_list, name='article_list'),
    path('article/<int:pk>/update/', article_update_view, name='article_update_view'),
    path('article/<int:pk>/delete/', article_delete_view, name='article_delete_view'),
    path('article/<int:pk>/hide/', article_hide_view, name='article_hide_view'),
    path('article/<int:pk>/unhide/', article_unhide_view, name='article_unhide_view'),
    
    path('knowledge/<int:pk>/', KnowledgeDetailView.as_view(), name='knowledge_detail'),
    path('create_knowledge/', create_knowledge, name='create_knowledge'),
    path('knowledge_list/', knowledge_list, name='knowledge_list'),
    



    path('manage/',manage_view,name='manage_view'),
    path('manage_request/',manage_request,name='manage_request'),
    path('rate/',rate_topic,name='rate-view'),



    

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quanlytruonghop/quanly/topicyeucau/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.validators import RegexValidator
from django.contrib.auth.models import Group
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import timedelta
from django.urls import reverse
import pytz

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Email field is required')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if not extra_fields.get('is_staff'):
            raise ValueError('Superuser must have is_staff=True')
        if not extra_fields.get('is_superuser'):
            raise ValueError('Superuser must have is_superuser=True')

        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    cus_id = models.CharField(max_length=10,default=0)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    role = models.CharField(max_length=10, choices=(('student', 'Student'), ('teacher', 'Teacher')), default='student')
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255,default='Họ và Tên')
    phone_regex = RegexValidator(regex=r'^\d{10}$', message="Số điện thoại phải có 10 chữ số.")
    phone = models.CharField(validators=[phone_regex], max_length=10, blank=True, null=True)
    student_id = models.CharField(max_length=10)
    course = models.CharField(max_length=50)
    avatar = models.ImageField(upload_to='avatars/', default='avatars/default.jpg')
    role = models.CharField(max_length=255, default='Sinh viên')
    

    def __str__(self):
        return self.user.username
    
class Knowledge(models.Model):
    category = models.CharField(max_length=255)
    content = models.CharField(max_length=255,blank=True,null=True)
    image = models.ImageField(upload_to='images/knowledge', blank=True, null=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    url = models.CharField(max_length=255,blank=True,null=True)
    

    def __str__(self):
        return self.category

class Article(models.Model):
    title = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    content = RichTextUploadingField(blank=True, null=True)
    image = models.ImageField(upload_to='articles/', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    views = models.PositiveIntegerField(default=0)
    like_count = models.PositiveIntegerField(default=0)
    hidden = models.BooleanField(default=False)
    knowledge = models.ForeignKey(Knowledge, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        if self.knowledge and self.knowledge.url:
            return self.knowledge.url
        return reverse('article_detail', args=[str(self.id)])

    

    def add_like(self, user):
        if user not in self.likes.all():
            self.likes.add(user)
            self.like_count += 1
            self.save()

    




class Image(models.Model):
    image = models.ImageField(upload_to='images/topic')

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    request_count = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name

class Topic(models.Model):
    TITLE_MAX_LENGTH = 200
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    content = RichTextUploadingField(blank=True, null=True)
    image = models.ImageField(upload_to='images/topic', blank=True, null=True, default=None)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='topics')
    start_time = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)


    def save(self, *args, **kwargs):
        # Tăng request_count của category liên kết
        self.category.request_count += 1
        self.category.save()
        super(Topic, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    




class MyTopic(models.Model):
    CHOICES = (
        ('Đang xử lý', 'Đang xử lý'),
        ('Hoàn thành', 'Hoàn thành'),
    )
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE) 
    employee = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    cus_id = models.CharField(max_length=20,blank=True) 
    status = models.CharField(max_length=20, choices=CHOICES, default='Chờ tiếp nhận')
    start_time = models.DateTimeField(auto_now_add=True)
    start_time_request= models.DateTimeField(null=True, blank=True)
    start_time_employee = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    elapsed_time = models.IntegerField(null=True, blank=True,default=0)

    def save(self, *args, **kwargs):
        if self.start_time_request and self.end_time:
            elapsed_time = self.end_time - self.start_time_request
            self.elapsed_time = int(elapsed_time.total_seconds() // 60)  # Chuyển đổi thành phút và chuyển thành số nguyên
        super().save(*args, **kwargs)
        
    def get_formatted_start_time_request(self):
        vietnam_tz = pytz.timezone('Asia/Ho_Chi_Minh')
        start_time_request = self.start_time_request.astimezone(vietnam_tz)
        return start_time_request.strftime("%d/%m/%Y %H:%M:%S")

    def get_formatted_start_time(self):
        vietnam_tz = pytz.timezone('Asia/Ho_Chi_Minh')
        start_time = self.start_time.astimezone(vietnam_tz)
        return start_time.strftime("%d/%m/%Y %H:%M:%S")

    def get_formatted_start_time_employee(self):
        vietnam_tz = pytz.timezone('Asia/Ho_Chi_Minh')
        start_time_employee = self.start_time_employee.astimezone(vietnam_tz)
        return start_time_employee.strftime("%d/%m/%Y %H:%M:%S")
    
    def get_formatted_end_time(self):
        vietnam_tz = pytz.timezone('Asia/Ho_Chi_Minh')
        end_time = self.end_time.astimezone(vietnam_tz)
        return end_time.strftime("%d/%m/%Y %H:%M:%S")

    def get_formatted_elapsed_time(self):
        hours = self.elapsed_time // 60
        minutes = self.elapsed_time % 60
        seconds = 0
        formatted_elapsed_time = "{:02d}:{:02d}:{:02d}".format(hours, minutes, seconds)
        return formatted_elapsed_time

    def __str__(self):
        return self.topic.title

    @property
    def topic_title(self):
        return self.topic.title
    
    @property
    def topic_content(self):
        return self.topic.content
    
    @property
    def topic_author(self):
        return self.topic.author

    @property
    def name(self):
        return self.employee.username if self.employee else ""
    



class Rating(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    score = models.IntegerField(default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0),
        ]
    )

    def __str__(self):
        return self.topic.title
    
    @property
    def topic_title(self):
        return self.topic.title
    
    @property
    def topic_content   (self):
        return self.topic.content
    
    @property
    def topic_author(self):
        return self.topic.author

    






class TopicSubmission(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    cus_id = models.CharField(max_length=20)
    status = models.CharField(max_length=20, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} - {self.topic.title}'
    

quanlytruonghop/quanly/topicyeucau/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Topic,UserProfile,Category,MyTopic,Article,Knowledge
from django.core.validators import RegexValidator
from django.contrib.auth.models import Group,User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserProfileForm(forms.ModelForm):
    phone = forms.CharField(label='Số điện thoại', max_length=10, validators=[RegexValidator('^[0-9]*$', 'Vui lòng chỉ nhập số')])
    
    class Meta:
        model = UserProfile
        fields = ('avatar', 'phone',)
        labels = {
            'avatar': 'Ảnh đại diện'
        }
        widgets = {
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'})
        }



class CustomModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        profile, created = UserProfile.objects.get_or_create(user=obj)
        return profile.name

class AssignTopicForm(forms.ModelForm):
    employee = CustomModelChoiceField(queryset=UserProfile.objects.all(), label='Nhân viên')

    class Meta:
        model = MyTopic
        fields = ['employee']
        labels = {
            'employee': 'Nhân viên',
        }

    def __init__(self, *args, **kwargs):
        self.is_end_time_updated = False
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['employee'].queryset = self.get_available_employees()

        self.is_end_time_updated = False

    def get_available_employees(self):
        employees = User.objects.filter(groups__name='Employee')
        if self.instance.pk:
            assigned_employees = MyTopic.objects.exclude(pk=self.instance.pk).filter(status='Đang xử lý').values_list('employee_id', flat=True)
            employees = employees.exclude(pk__in=assigned_employees)
        return employees
    
    def clean_employee(self):
        employee = self.cleaned_data['employee']
        if employee is not None:
            self.instance.status = 'Đang xử lý'
            self.instance.start_time_employee = timezone.now()
            # Tạo UserProfile nếu chưa tồn tại
            UserProfile.objects.get_or_create(user=employee)
        return employee

    
    def clean(self):
        cleaned_data = super().clean()
        status = cleaned_data.get('status')
        if status == 'Hoàn thành' and not self.is_end_time_updated:
            self.instance.status = status
            self.instance.end_time = timezone.now()
            self.is_end_time_updated = True
        return cleaned_data

class KnowledgeForm(forms.ModelForm):
    class Meta:
        model = Knowledge
        fields = ['category', 'content', 'image']
        labels = {
            'category': 'Thể loại',
            'content':'Nội dung',
            'image':'Hình ảnh',
        }
    

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {
            'name':'Tên thể loại',
        }  
    
    
class ArticleForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget(config_name='default'))
    class Meta:
        model = Article
        fields = ['title', 'category','content', 'image','knowledge']
        labels = {
            'title':'Chủ đề',
            'category': 'Thể loại',
            'content':'Nội dung',
            'image':'Hình ảnh',
            'knowledge':'Knowledge',
        }



class TopicForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget(config_name='default'))
    category = forms.ModelChoiceField(queryset=Category.objects.all(), to_field_name='name')

    class Meta:
        model = Topic
        fields = ['title', 'category','content', 'image']
        labels = {
            'title':'Chủ đề',
            'category': 'Thể loại',
            'content':'Nội dung',
            'image':'Hình ảnh',
        }

quanlytruonghop/quanly/topicyeucau/templates/client/account/account.html
{% extends 'client/base.html' %}
{% load static %}

{% block title %}{{request.user.username}}{% endblock %}

{% block style %}
<style>
    .container {
    margin-top: 100px;
    text-align: center;
    
  }
  img{
    overflow: hidden !important;
  }


</style>
{% endblock %}

{% block body %}
<div class="container">
  <h1>Thông tin tài khoản</h1>
  {% if request.user.is_authenticated %}
    {% if request.user.userprofile %}
      <img src="{{ request.user.userprofile.avatar.url }}" alt="Avatar" class="img-fluid rounded-circle" height="100px" width="200px">
      <h3>{{ request.user.userprofile.fullname }}</h3>
      <p><strong>ID:</strong> {{ request.user.userprofile.student_id }}</p>
      <p><strong>Khóa học:</strong> {{ request.user.userprofile.course }}</p>
      {% if user.is_authenticated%}
        <a href="{% url 'update_profile' %}" class="btn btn-primary">Cập nhật thông tin</a>
      {% endif %}
      
    {% else %}
      <h3>{{ request.user.username }}</h3>
      <p>Thông tin tài khoản chưa được cập nhật.</p>
      {% if user.is_authenticated %}
        <a href="{% url 'update_profile' %}" class="btn btn-primary">Cập nhật thông tin</a>
      {% endif %}
      
    {% endif %}
  {% else %}
    <p>Vui lòng <a href="{% url 'login' %}">đăng nhập</a> để xem thông tin tài khoản.</p>
  {% endif %}

</div>
{% endblock %}

quanlytruonghop/quanly/topicyeucau/templates/client/account/update_profile.html
{% extends 'client/base.html' %}
{% load static %}

{% block title %}Thông tin tài khoản{% endblock %}

{% block style %}

<style>
    .form-group label {
        font-weight: bold;

    }

    .form-group {
        padding: 10px;
        font-size: 20px;
    }

    .avatar-preview {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 200px;
        height: 200px;
        overflow: hidden;
        margin-bottom: 20px;
        margin-left: auto;
        margin-right: auto;
        border-radius: 50%;

    }

    .avatar-preview img {
        max-width: 100%;
        max-height: 100%;
    }


    .button-group {
        margin-top: 20px;
    }

    .custom-margin {
        margin-top: 60px !important;
    }

    footer.text-center.text-lg-start.custom-footer {
        margin-top: 274px;
    }

    @media (max-width: 768px) {
        .avatar-preview {
            width: 150px;
            height: 150px;
        }
    }

    .info {
        text-align: center;
        margin-top: 10px;
    }

    .info div {
        margin-bottom: 5px;
        font-size: 15px;

    }

    .text-center-mobile {
        text-align: center;
    }

    @media (min-width: 768px) {
        .text-center-mobile {
            text-align: left;
        }
    }

    .info-email {
        font-weight: 600;
    }
</style>
{% endblock %}

{% block body %}
<div class="wrapper"></div>
<div class="container mt-5 custom-margin">
    <h1 class="text-center-mobile" style="padding: 25px;">Thông tin tài khoản</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <div class="avatar-preview">
                    {% if form.instance.avatar %}
                    <div class="avatar-img">
                        <img src="{{ form.instance.avatar.url }}" alt="Avatar preview">
                    </div>
                    {% else %}
                    <div class="avatar-img">
                        <img src="{% static 'img/default-avatar.png' %}" alt="Default avatar preview">
                    </div>
                    {% endif %}
                </div>
                <div class="info">
                    <div class="info-email">{{ request.user.email }}</div>
                    <div>{{ request.user.userprofile.student_id }}</div>
                </div>
                <div class="form-group">
                    <input type="file" name="avatar" accept="image/*" id="id_avatar" style="display: none;">
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label for="id_student_id">Họ và Tên:</label>
                    {{ request.user.userprofile.name }}
                </div>
                <div class="form-group">
                    <label for="id_student_id">Mã sinh viên:</label>
                    {{ request.user.userprofile.student_id }}
                </div>
                <div class="form-group">
                    <label for="id_course">Khóa học:</label>
                    {{ request.user.userprofile.course }}
                </div>
                <div class="form-group">
                    <label for="id_phone">Số điện thoại:</label>
                    {% if request.microsoft_user.mobilephone %}
                        {{ request.microsoft_user.mobilephone }}
                    {% else %}
                        {{ form.phone }}
                    {% endif %}
                </div>
                <div class="form-group button-group">
                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                    <a href="{% url 'account_profile' %}" class="btn btn-secondary">Hủy bỏ</a>
                </div>
            </div>
        </div>
    </form>
</div>




<script>
    const avatarPreview = document.querySelector('.avatar-preview');
    const avatarInput = document.querySelector('#id_avatar');

    avatarPreview.addEventListener('click', () => {
        avatarInput.click();
    });

    avatarInput.addEventListener('change', (event) => {
        const file = event.target.files[0];
        const reader = new FileReader();

        reader.onload = () => {
            const img = document.createElement('img');
            img.src = reader.result;
            avatarPreview.querySelector('.avatar-img').innerHTML = '';
            avatarPreview.querySelector('.avatar-img').appendChild(img);
        };

        reader.readAsDataURL(file);
    });
</script>
{% endblock %}